name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: "uzh"
        password: ${{ secrets.SSH_SCRET }}
        port: ${{ secrets.SERVER_PORT }} # опціонально, якщо ви не використовуєте стандартний порт 22
        script: |
          cd /home/uzh/uzh
          git clean -fdx
          git pull uzh-oblik-back main
          docker build -t flask-app .  
          docker stop flask-app || true
          docker rm flask-app || true 
          docker run -d -p 5001:5000 --name flask-app -e secret_key="${{ secrets.SECRET_KEY }}" -e db_password="${{ secrets.PG_PASS }}" flask-app
